### ISSUE TITLE
کمک در نرم افزار ساخت مقاطع

### ISSUE THREAD

**Issue by alimomen2000** [ebrahimraeyat/Civil#13]
سلام مهندس جان
ممنون از زحماتت
من توی نرم افزار ساخت مقاطع دکمه حذف مقطع ندیدم . نتونستم مقطعی رو که اشتباهی ساختم حذف کنم. لطفا راهنمایی بفرمایید
مورد بعدی اینکه مقاطع دوبل با فاصله صفر ساخته نمیشه و خروجی اکسل هم کار نمیکنه. آدرس میگیره و فایلی تولید نمیشه
و مورد آخر اینکه فایل پراپری که گذاشتید وقتی باز میکنم ایراد لایسنس میگیره و نمیدونم از چیه

**Comment by ebrahimraeyat** [comment]
سلام. 
۱- دکمه حذف رو اضافه کردم 
۲- آره، تو فاصله صفر مشکل داشت، درستش کردم.
۳- برای خروجی اکسل دستور زیر رو توی پوشه bin بزن:
python -m pip install openpyxl

**Comment by ebrahimraeyat** [comment]
مورد j رو در [این](https://github.com/ebrahimraeyat/Civil/commit/df822b36b725c64c42ab0d8b6a00c3754d29ab15) آدرس درست کردم: 

کلیدها رو هم در [این](https://github.com/ebrahimraeyat/Civil/commit/ad92ceb613fda42ef8e1b8cb22d3008abfb324e2)  آدرس

**Comment by ebrahimraeyat** [comment]
@alimomen2000  مهندس جان اون مورد فکر نکنم ایراد لایسنس باشه، میشه ایراد رو بزارید؟

**Comment by ebrahimraeyat** [comment]
that works correctly.
