### ISSUE TITLE
Adding UPA section

### ISSUE THREAD

**Issue by AliranjbarCivil** [ebrahimraeyat/Civil#2]
با سلام خدمت جناب آقای مهندس عزیز 
با تشکر ویژه بابت طراحی نرم افزار ساخت مقاطع فولادی 
پس از بررسی اجمالیی نرم افزار متوجه نبود مقاطع ناودانی ایرانی شدم لذا خواهشمندم در ویرایش های بعدی این مقاطع رو به قابلیت های نرم افزار اضافه کنید.
ممنون
![upa](https://user-images.githubusercontent.com/44951744/48602539-b2d61a00-e988-11e8-9b0b-97031effb855.jpg)

**Comment by AliranjbarCivil** [comment]
با سلام خدمت جناب آقای مهندس عزیز
با تشکر ویژه بابت طراحی نرم افزار ساخت مقاطع فولادی
پس از بررسی اجمالی نرم افزار متوجه نبود مقاطع زنبوری شدم لذا خواهشمندم در ویرایش های بعدی این مقاطع رو به قابلیت های نرم افزار اضافه کنید.
ممنون

**Comment by AliranjbarCivil** [comment]
با سلام خدمت جناب آقای مهندس عزیز
با تشکر ویژه بابت طراحی نرم افزار ساخت مقاطع فولادی
پس از بررسی اجمالیی نرم افزار متوجه عدم امکان محاسبه مشخصات مکانیکی از جله ثابت پیچش و ثابت تابیدگی توسط نرم افزار شدم لذا در صورت امکان در ویرایش های بعدی موارد فوق الذکر رو به قابلیت های نرم افزار اضافه کنید.
ممنون

**Comment by ebrahimraeyat** [comment]
> با سلام خدمت جناب آقای مهندس عزیز
> با تشکر ویژه بابت طراحی نرم افزار ساخت مقاطع فولادی
> پس از بررسی اجمالی نرم افزار متوجه نبود مقاطع زنبوری شدم لذا خواهشمندم در ویرایش های بعدی این مقاطع رو به قابلیت های نرم افزار اضافه کنید.
> ممنون

Thanks. For CPE, i added those in ver1.2. now those are supported.

**Comment by ebrahimraeyat** [comment]
If anyone please send me properties of UPA section in this format. units are in mm:

 # name, area, bf,   d,    xm,     Ix,      Iy,     Zx,   Zy, tf, tw
 UNP8 = Unp("UNP08", 1102, 45, 80, 14.44, 1058000, 194000, 32810, 13350, 8, 6)
UNP10 = Unp("UNP10", 1346, 50, 100, 15.45, 2053000, 292900, 50330, 18000, 8.5, 6)
UNP12 = Unp("UNP12", 1698, 55, 120, 15.98, 3641000, 431400, 74690, 23630, 9, 7)
UNP14 = Unp("UNP14", 2036, 60, 140, 17.5, 6044000, 626000, 105400, 31430, 10, 7)
        UNP16 = Unp("UNP16", 2402, 65, 160, 18.32, 9246000, 853900, 141100, 39120, 10.5, 7.5)
        UNP18 = Unp("UNP18", 2796, 70, 180, 19.19, 1.353e7, 1137000, 183600, 48040, 11, 8)
        UNP20 = Unp("UNP20", 3219, 75, 200, 20.07, 1.911e7, 1483000, 233500, 58040, 11.5, 8.5)
        UNP22 = Unp("UNP22", 3744, 80, 220, 21.36, 2.691e7, 1966000, 298800, 71870, 12.5, 9)
        UNP24 = Unp("UNP24", 4229, 85, 240, 22.26, 3.597e7, 2479000, 366400, 84830, 13, 9.5)
        UNP26 = Unp("UNP26", 4827, 90, 260, 23.57, 4.821e7, 3178000, 453100, 102500, 14, 10)
        UNP28 = Unp("UNP28", 5340, 95, 280, 25.2, 6.272e7, 3989000, 544500, 122300, 15, 10)

xm = ez in stahl. these are for UNPs.
        UNP30 = Unp("UNP30", 5874, 100, 300, 26.87, 8.022e7, 4940000, 646900, 144600, 16, 10)

**Comment by salmanishere** [comment]
Can you also introduce a reference text? Where should we find the properties of UNPs?
