### ISSUE TITLE
Why do you use pyside2 and not pyside?

### ISSUE THREAD

**Issue by salmanishere** [ebrahimraeyat/Civil#20]
As can be seen [here](https://github.com/FreeCAD/FreeCAD/blob/master/requirements.txt) FreeCAD depends on pyside (qt4) but your workbench depends on pyside2 (qt5). Why is it so?

**Comment by ebrahimraeyat** [comment]
pyside is for official release of freecad that is 0.17 and also use python 2.
but civil works on freecad 0.18 that require pyside2 and python3.

**Comment by salmanishere** [comment]
thanks.
