### ISSUE TITLE
define source code encoding wherever you use Non-ASCII characters

### ISSUE THREAD

**Issue by salmanishere** [ebrahimraeyat/Civil#21]
you'd better define UTF-8 encoding whenever you use Non-[ASCII](https://en.wikipedia.org/wiki/ASCII) characters in your source code, like [this file](https://github.com/ebrahimraeyat/Civil/blob/5d0a3829596e20fd139d9c73d0b3398fb189505f/taskPanel.py#L412). Otherwise, the users may get an encoding error.

just add this line to tho top of your source code: `# -*- coding: utf-8 -*-`.

more info: https://www.python.org/dev/peps/pep-0263/

**Comment by ebrahimraeyat** [comment]
yes, but default major python version for this application is python3 that knows all of string with utf8.

**Comment by salmanishere** [comment]
Oh, sorry. You're right. This has changed in python3. You can't teach an old dog new tricks :)

https://www.python.org/dev/peps/pep-3120/
