### ISSUE TITLE
add instructions on how to install on Debian 10 (Buster)

### ISSUE THREAD

**Issue by salmanishere** [ebrahimraeyat/Civil#24]
A version of FreeCAD, which is compiled against Python3, is available in Debian 10 repositories. So it would be nice if we add the installation instructions to the README.

**Comment by ebrahimraeyat** [comment]
Thanks. is it work for you? because Civil needs openpyxl and xlrd too!

**Comment by ebrahimraeyat** [comment]
also I think it is better for installation of FreeCAD we refer to freecad github page for 0.18_pre:
https://github.com/FreeCAD/FreeCAD/releases

and i have been inserted requirement.txt in root of project that can be used for dependencies.

`"..\..\bin\python" -m pip install -r requirements.txt`

can you please test it under debian linux with this instruction and correct ReadMe file?
thanks.

**Comment by salmanishere** [comment]
> Thanks. is it work for you? because Civil needs openpyxl and xlrd too!

Where have you used these two packages? Because as I searched in your source code but I couldn't find where they have been imported!

**Comment by salmanishere** [comment]
Personally I prefer to install packages from the official distro repos, it is safer and causes less headache in managing the whole operating system. When there is the preferred version of FreeCAD in the Debian Buster repo I see no reason to install it directly from the freecad website. Soon, Ubuntu will also mirror this package from Debian repositories and it will be available in newer versions of Ubuntu.

For other GNU/Linux distributions, I agree with you to install this AppImage because there is no other option except compiling everything.

**Comment by ebrahimraeyat** [comment]
> > Thanks. is it work for you? because Civil needs openpyxl and xlrd too!
> 
> Where have you used these two packages? Because as I searched in your source code, I couldn't find where they have been imported!
> 
> This is what I see after clicking on _create section_ from _civil_ menu.
> ![freecad-civil-mod](https://user-images.githubusercontent.com/45880325/54016912-bcc49880-4184-11e9-8a99-c12e2484dba6.png)

Thanks. oh. yes. those packages install throw another package. because i use pynsist for generating windows version, I must explicit select all of packages, It can not recognise dependency for packages.
thank you so much.

**Comment by ebrahimraeyat** [comment]
> Personally I prefer to install packages from the official distro repos, it is safer and causes less headache in managing the whole operating system. When there is the preferred version of FreeCAD in the Debian Buster repo I see no reason to install it directly from the freecad website. Soon, Ubuntu will also mirror this package from Debian repositories and it will be available in newer versions of Ubuntu.
> 
> For other GNU/Linux distributions, I agree with you to install this AppImage because there is no other option except compiling everything.
> 
> I can add two sections, one for Debian Buster (where everything is in the repos) and another section for other distributions, which they need to download FreeCAD from its own website.

you are right. I install AppImage on my ubuntu system and it's not working!

**Comment by ebrahimraeyat** [comment]
done in https://github.com/ebrahimraeyat/Civil/commit/2cba5f5f40d0a00da0f66d47611c3a2abd956ffc
