### ISSUE TITLE
Convert tab indentations to spaces

### ISSUE THREAD

**Issue by luzpaz** [ebrahimraeyat/Civil#29]
Some files use tabs to indent while others use spaces. The reason for this is certain editors display indentations differently. Please consider using spaces. In many editors there is an option to `Convert Indentation to Spaces` to automatically change the file.

Locations:
```
./civil_update.py
./safe/punch/*
```

**Comment by ebrahimraeyat** [comment]
Thanks you so much. I am working on strip branch and will correct this.

**Comment by ebrahimraeyat** [comment]
applied at https://github.com/ebrahimraeyat/Civil/commit/a71d45f2fe23003fd11dcb5a3cce04c97a630973
