### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by luzpaz** [ebrahimraeyat/Civil#5]
Uploaded screenshot files for README.md
![image](https://user-images.githubusercontent.com/4140247/48372017-4d81e080-e68b-11e8-9f97-ff12c3c275b3.png)

![image](https://user-images.githubusercontent.com/4140247/48372005-4529a580-e68b-11e8-84c4-4b3f50789229.png)

**Comment by ebrahimraeyat** [comment]
Hi @luzpaz . Thanks a lot for your help.
![3d](https://user-images.githubusercontent.com/8196112/48443187-3674e880-e788-11e8-9eec-3668095d8f65.png)
![plansafe](https://user-images.githubusercontent.com/8196112/48443232-53112080-e788-11e8-84e7-1cc939a87d72.png)
![sec1](https://user-images.githubusercontent.com/8196112/48443434-0b3ec900-e789-11e8-8b36-5a467a58bea7.png)
![sec2](https://user-images.githubusercontent.com/8196112/48443436-0d088c80-e789-11e8-83d0-7ae5100769fe.png)

**Comment by ebrahimraeyat** [comment]
![3d](https://user-images.githubusercontent.com/8196112/48443621-aa63c080-e789-11e8-9760-f912d981232b.png)
![sec3](https://user-images.githubusercontent.com/8196112/48443669-d5e6ab00-e789-11e8-900a-b6c4f9de6ada.png)
